/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import model.Asistente;
import persistence.InscripcionDAO;
import persistence.AsistenteDAO;
import java.util.List;
import java.util.ArrayList;
/**
 *
 * @author p4prika
 */
public class CancelarInscripcionTaller extends javax.swing.JFrame {
    private Asistente alumnoSeleccionado;
    private InscripcionDAO inscripcionDAO;
    private AsistenteDAO alumnoDAO;
    /**
     * Creates new form CancelarInscripcionTaller
     */
    public CancelarInscripcionTaller() {
        initComponents();
        habilitarCamposInformacion(false);
        setTitle("Casa de la Cultura – UAM Azcapotzalco:: Cancelar inscripcion a talleres");
        this.setLocationRelativeTo(null);
        jButton_baja_danza.setEnabled(false);
        jButton_baja_teatro.setEnabled(false);
        jButton_baja_dibujo.setEnabled(false);
        jButton_baja_redaccion.setEnabled(false);
        jButton_baja_lectura.setEnabled(false);
        //jButton_aplicar.setEnabled(false);
        inscripcionDAO = new InscripcionDAO();
        alumnoDAO = new AsistenteDAO();
        
        jTextField_1er_apellido.setEditable(false);
        jTextField_2do_apellido.setEditable(false);
        jTextField_direccion.setEditable(false);
        jTextField_edad.setEditable(false);
        jTextField_genero.setEditable(false);
        jTextField_nombre.setEditable(false);
        jTextField_tel_contacto.setEditable(false);
        jTextField_tel_emergencia.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton_buscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_1er_apellido = new javax.swing.JTextField();
        jTextField_2do_apellido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_edad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField_genero = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField_tel_contacto = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField_tel_emergencia = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField_direccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton_baja_teatro = new javax.swing.JButton();
        jButton_baja_dibujo = new javax.swing.JButton();
        jButton_baja_redaccion = new javax.swing.JButton();
        jButton_baja_lectura = new javax.swing.JButton();
        jButton_baja_danza = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        jLabel1.setText("Buscar asistente por matricula");

        jButton_buscar.setBackground(new java.awt.Color(255, 51, 51));
        jButton_buscar.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jButton_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_buscar.setText("Buscar");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Nombre(s):");

        jLabel10.setText("Primer apellido:");

        jLabel11.setText("Segundo apellido:");

        jLabel12.setText("Edad:");

        jLabel13.setText("Genero:");

        jLabel14.setText("Telefono de contacto:");

        jLabel15.setText("Telefono de emergencia:");

        jLabel16.setText("Direccion:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_nombre)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_edad, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                .addComponent(jTextField_1er_apellido)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jTextField_tel_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_2do_apellido)
                            .addComponent(jTextField_genero)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11))
                                .addGap(0, 154, Short.MAX_VALUE))
                            .addComponent(jTextField_tel_emergencia)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField_direccion))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_1er_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_2do_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_tel_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_tel_emergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Talleres inscritos");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Danza");

        jLabel5.setText("Teatro");

        jLabel6.setText("Dibujo");

        jLabel7.setText("Redaccion");

        jLabel8.setText("Lectura");

        jButton_baja_teatro.setBackground(new java.awt.Color(255, 51, 51));
        jButton_baja_teatro.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton_baja_teatro.setForeground(new java.awt.Color(255, 255, 255));
        jButton_baja_teatro.setText("Baja de inscripcion");
        jButton_baja_teatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_baja_teatroActionPerformed(evt);
            }
        });

        jButton_baja_dibujo.setBackground(new java.awt.Color(255, 51, 51));
        jButton_baja_dibujo.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton_baja_dibujo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_baja_dibujo.setText("Baja de inscripcion");
        jButton_baja_dibujo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_baja_dibujoActionPerformed(evt);
            }
        });

        jButton_baja_redaccion.setBackground(new java.awt.Color(255, 51, 51));
        jButton_baja_redaccion.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton_baja_redaccion.setForeground(new java.awt.Color(255, 255, 255));
        jButton_baja_redaccion.setText("Baja de inscripcion");
        jButton_baja_redaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_baja_redaccionActionPerformed(evt);
            }
        });

        jButton_baja_lectura.setBackground(new java.awt.Color(255, 51, 51));
        jButton_baja_lectura.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton_baja_lectura.setForeground(new java.awt.Color(255, 255, 255));
        jButton_baja_lectura.setText("Baja de inscripcion");
        jButton_baja_lectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_baja_lecturaActionPerformed(evt);
            }
        });

        jButton_baja_danza.setBackground(new java.awt.Color(255, 51, 51));
        jButton_baja_danza.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton_baja_danza.setForeground(new java.awt.Color(255, 255, 255));
        jButton_baja_danza.setText("Baja de inscripcion");
        jButton_baja_danza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_baja_danzaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_baja_teatro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_baja_dibujo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_baja_redaccion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_baja_lectura, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_baja_danza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton_baja_danza))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton_baja_teatro))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButton_baja_dibujo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton_baja_redaccion))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jButton_baja_lectura))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jLabel3.setText("Informacion del asistente");

        jButton_cancelar.setBackground(new java.awt.Color(255, 51, 51));
        jButton_cancelar.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cancelar.setText("Salir");
        jButton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_buscar)))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
                null,
                "¿Estás seguro de que deseas cancelar la operacion?",
                "Cancelar",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            System.out.println("Registro cancelado. Redirigiendo al dashboard...");
            //new LoginForm().setVisible(true);
            this.dispose();
            // Aquí puedes llamar a tu método para cerrar sesión o abrir la pantalla de login
        } else {
            System.out.println("Operación cancelada.");
        }
    }//GEN-LAST:event_jButton_cancelarActionPerformed
    
    public void llenarTextFields(Asistente asistente) {
        jTextField_1er_apellido.setText(asistente.getPrimerApellido()); 
        jTextField_2do_apellido.setText(asistente.getSegundoApellido());
        jTextField_direccion.setText(asistente.getDireccion());
        jTextField_edad.setText(Integer.toString(asistente.getEdad()));
        jTextField_genero.setText(asistente.getGenero());
        jTextField_nombre.setText(asistente.getNombre());
        jTextField_tel_contacto.setText(asistente.getTelefonoContacto());
        jTextField_tel_emergencia.setText(asistente.getTelefonoEmergencia());
    }
    
    private void habilitarCamposInformacion(boolean isEnable) {
        jTextField_1er_apellido.setEnabled(isEnable); 
        jTextField_2do_apellido.setEnabled(isEnable);
        //jTextField_costo_actual.setEnabled(isEnable);
        jTextField_direccion.setEnabled(isEnable);
        jTextField_edad.setEnabled(isEnable);
        jTextField_genero.setEnabled(isEnable);
        jTextField_nombre.setEnabled(isEnable);
        jTextField_tel_contacto.setEnabled(isEnable);
        jTextField_tel_emergencia.setEnabled(isEnable);
        //jTextArea_talleres_inscritos.setEnabled(isEnable);
    }
    
    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here:
        String matricula = jTextField1.getText().trim();
        if (matricula.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese una matrícula.", 
                                                      "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            jTextField_1er_apellido.setText("");
            jTextField_2do_apellido.setText("");
            jTextField_direccion.setText("");
            jTextField_edad.setText("");
            jTextField_genero.setText("");
            jTextField_nombre.setText("");
            jTextField_tel_contacto.setText("");
            jTextField_tel_emergencia.setText("");
            habilitarCamposInformacion(false);
            return;
        }

        alumnoSeleccionado = alumnoDAO.buscarAsistentePorMatricula(matricula);
        if (alumnoSeleccionado != null && alumnoSeleccionado.getIdAlumno() > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Alumno encontrado: " + alumnoSeleccionado.getNombre() + " " + 
                                                      alumnoSeleccionado.getPrimerApellido() + " (ID: " + alumnoSeleccionado.getIdAlumno() + ")", 
                                                      "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            llenarTextFields(alumnoSeleccionado);
            habilitarCamposInformacion(true);
            List<Integer> talleresInscritos = inscripcionDAO.obtenerTalleresInscritos(alumnoSeleccionado.getIdAlumno());          
            jButton_baja_danza.setEnabled(false);
            jButton_baja_teatro.setEnabled(false);
            jButton_baja_dibujo.setEnabled(false);
            jButton_baja_redaccion.setEnabled(false);
            jButton_baja_lectura.setEnabled(false);
        
            for (Integer idTaller : talleresInscritos) {
                switch (idTaller) {
                    case 1: case 2: // Danza
                        jButton_baja_danza.setEnabled(true);
                        break;
                    case 3: case 4: // Lectura
                        jButton_baja_lectura.setEnabled(true);
                        break;
                    case 5: case 6: // Redacción
                        jButton_baja_redaccion.setEnabled(true);
                        break;
                    case 7: case 8: // Dibujo
                        jButton_baja_dibujo.setEnabled(true);
                        break;
                    case 9: case 10: // Teatro
                        jButton_baja_teatro.setEnabled(true);
                        break;
                    case 0:
                        javax.swing.JOptionPane.showMessageDialog(this, "El alumno no esta inscrito a ningun taller", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
                        break;
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró un alumno con esa matrícula o el ID es inválido.", 
                                                  "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            alumnoSeleccionado = null;
            
            jTextField_1er_apellido.setText("");
            jTextField_2do_apellido.setText("");
            jTextField_direccion.setText("");
            jTextField_edad.setText("");
            jTextField_genero.setText("");
            jTextField_nombre.setText("");
            jTextField_tel_contacto.setText("");
            jTextField_tel_emergencia.setText("");
            
            jButton_baja_danza.setEnabled(false);
            jButton_baja_teatro.setEnabled(false);
            jButton_baja_dibujo.setEnabled(false);
            jButton_baja_redaccion.setEnabled(false);
            jButton_baja_lectura.setEnabled(false);
            habilitarCamposInformacion(false);
        }
    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jButton_baja_danzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_baja_danzaActionPerformed
        // TODO add your handling code here:
        darDeBajaTaller(alumnoSeleccionado.getIdAlumno(), 1, "Danza");  
    }//GEN-LAST:event_jButton_baja_danzaActionPerformed

    private void jButton_baja_teatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_baja_teatroActionPerformed
        // TODO add your handling code here:
        darDeBajaTaller(alumnoSeleccionado.getIdAlumno(), 9, "Teatro");        
    }//GEN-LAST:event_jButton_baja_teatroActionPerformed

    private void jButton_baja_dibujoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_baja_dibujoActionPerformed
        // TODO add your handling code here:
        darDeBajaTaller(alumnoSeleccionado.getIdAlumno(), 7, "Dibujo");
    }//GEN-LAST:event_jButton_baja_dibujoActionPerformed

    private void jButton_baja_redaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_baja_redaccionActionPerformed
        // TODO add your handling code here:
        darDeBajaTaller(alumnoSeleccionado.getIdAlumno(), 5, "Redacción");
    }//GEN-LAST:event_jButton_baja_redaccionActionPerformed

    private void jButton_baja_lecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_baja_lecturaActionPerformed
        // TODO add your handling code here:
        darDeBajaTaller(alumnoSeleccionado.getIdAlumno(), 3, "Lectura");
    }//GEN-LAST:event_jButton_baja_lecturaActionPerformed
    
    private void darDeBajaTaller(int idAlumno, int idTaller, String nombreTaller) {
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog( 
                this,
                "¿Estás seguro de que deseas cancelar la inscripción al taller de " + nombreTaller + "?",
                "Cancelar inscripción",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            // Buscar id_inscripcion
            String sql = "SELECT id_inscripcion FROM inscripcion WHERE id_alumno = ? AND id_taller = ?";
            try (java.sql.PreparedStatement stmt = inscripcionDAO.getConnection().prepareStatement(sql)) {
                stmt.setInt(1, idAlumno);
                stmt.setInt(2, idTaller);
                java.sql.ResultSet rs = stmt.executeQuery();
                if (rs.next()) {
                    int idInscripcion = rs.getInt("id_inscripcion");
                    if (inscripcionDAO.eliminar(idInscripcion)) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Inscripción al taller de " + nombreTaller + " eliminada correctamente.", 
                                                                  "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        // Deshabilitar el botón correspondiente
                        switch (idTaller) {
                            case 1: case 2: jButton_baja_danza.setEnabled(false); break;
                            case 3: case 4: jButton_baja_lectura.setEnabled(false); break;
                            case 5: case 6: jButton_baja_redaccion.setEnabled(false); break;
                            case 7: case 8: jButton_baja_dibujo.setEnabled(false); break;
                            case 9: case 10: jButton_baja_teatro.setEnabled(false); break;
                        }
                        habilitarCamposInformacion(false);
                        jTextField1.setText("");
                        jTextField_1er_apellido.setText("");
                        jTextField_2do_apellido.setText("");
                        jTextField_direccion.setText("");
                        jTextField_edad.setText("");
                        jTextField_genero.setText("");
                        jTextField_nombre.setText("");
                        jTextField_tel_contacto.setText("");
                        jTextField_tel_emergencia.setText("");
                        jButton_baja_danza.setEnabled(false);
                        jButton_baja_teatro.setEnabled(false);
                        jButton_baja_dibujo.setEnabled(false);
                        jButton_baja_redaccion.setEnabled(false);
                        jButton_baja_lectura.setEnabled(false);
                        
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar la inscripción.", 
                                                                  "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "No se encontró la inscripción para este taller.", 
                                                              "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            } catch (java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage(), 
                                                          "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelarInscripcionTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelarInscripcionTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelarInscripcionTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelarInscripcionTaller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelarInscripcionTaller().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_baja_danza;
    private javax.swing.JButton jButton_baja_dibujo;
    private javax.swing.JButton jButton_baja_lectura;
    private javax.swing.JButton jButton_baja_redaccion;
    private javax.swing.JButton jButton_baja_teatro;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_1er_apellido;
    private javax.swing.JTextField jTextField_2do_apellido;
    private javax.swing.JTextField jTextField_direccion;
    private javax.swing.JTextField jTextField_edad;
    private javax.swing.JTextField jTextField_genero;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_tel_contacto;
    private javax.swing.JTextField jTextField_tel_emergencia;
    // End of variables declaration//GEN-END:variables
}
