/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author p4prika
 */
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;

import forms.LoginForm;
import forms.AnadirAsistente;
import forms.ActualizarAsistente;
import forms.EliminarAsistente;
import forms.InscripcionTaller;
import forms.CancelarInscripcionTaller;

import javax.swing.table.DefaultTableModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import model.InscripcionReporte;
import persistence.InscripcionDAO;

public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    // default border for the menu items
    private InscripcionDAO inscripcionDAO;
    Border default_border = BorderFactory.createMatteBorder(1, 0, 1, 0, new Color(46, 49, 49));

    // yellow border for the menu items
    Border yellow_border = BorderFactory.createMatteBorder(1, 0, 1, 0, Color.YELLOW);

    javax.swing.JLabel[] menuLabels;
    javax.swing.JPanel[] panels;

    public Dashboard() {
        initComponents();
        this.setTitle("Casa de la Cultura – UAM Azcapotzalco: Dashboard");
        
        inscripcionDAO = new InscripcionDAO();
        //cargarAsistentesEnTabla();
        jTable5_informacion_asistentes.setDefaultEditor(Object.class, null);
        // Añadir listener para selección de renglón
        jTable5_informacion_asistentes.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    mostrarInformacionSeleccionada();
                }
            }
        });
        // center this form
        this.setLocationRelativeTo(null);

        // set borders
        // panel logo border
        Border panelBorder = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.lightGray);
        jPanel_logoANDname.setBorder(panelBorder);
        // panel container border
        Border containerBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(46, 49, 49));
        jPanel_container.setBorder(containerBorder);

        // create an array of jlabels
        menuLabels = new javax.swing.JLabel[6];
        // Populate the menuLabels array
        menuLabels[0] = Label_menuItem1;
        menuLabels[1] = Label_menuItem2;
        menuLabels[2] = Label_menuItem3;
        menuLabels[3] = Label_menuItem4;
        menuLabels[4] = Label_menuItem5;
        menuLabels[5] = Label_menuItem6;

        /*for (JLabel label : menuLabels) {
            if (label != null) {
                label.setOpaque(true);
            }
        }*/
        panels = new javax.swing.JPanel[6];

        // Populate the panels array
        panels[0] = jPanel1_dashboard;
        panels[1] = jPanel2_users;
        panels[2] = jPanel3_registro_asistentes;
        panels[3] = jPanel4_inscripcion_asistentes;
        panels[4] = jPanel5_info;
        panels[5] = jPanel6_exportar;

        // Oculta todos los paneles menos el dashboard al iniciar
        showPanel(jPanel1_dashboard);

        // Agrega los listeners para hacer clic en los labels
        addActionToMenuLabels();
        //addListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel_container = new javax.swing.JPanel();
        jPanel_logoANDname = new javax.swing.JPanel();
        jLabel_appLogo = new javax.swing.JLabel();
        jButton1_logout = new javax.swing.JButton();
        jPanel_menu = new javax.swing.JPanel();
        Label_menuItem1 = new javax.swing.JLabel();
        Label_menuItem2 = new javax.swing.JLabel();
        Label_menuItem3 = new javax.swing.JLabel();
        Label_menuItem4 = new javax.swing.JLabel();
        Label_menuItem5 = new javax.swing.JLabel();
        Label_menuItem6 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel1_dashboard = new javax.swing.JPanel();
        jPanel1_danza = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1_teatro = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1_dibujo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1_readaccion = new javax.swing.JPanel();
        jLabel_inscritos_dibujo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1_lectura = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2_users = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4_inscripcion_asistentes = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton4_inscribir_taller = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton4_cancelar_inscripcion_taller = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3_registro_asistentes = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton3_registrar_asistente = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3_actualizar_asistente = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3_eliminar_asistente = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel5_info = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable5_informacion_asistentes = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5_info_buscar = new javax.swing.JTextField();
        jButton5_info_buscar = new javax.swing.JButton();
        jPanel6_exportar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel_container.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_logoANDname.setBackground(new java.awt.Color(255, 51, 51));

        jLabel_appLogo.setIcon(new javax.swing.ImageIcon("/home/p4prika/Documents/Github/Casa-Cultura-UAM/assets/uam_azcapo_logoRedim.png")); // NOI18N
        jLabel_appLogo.setText("LOGO");

        jButton1_logout.setText("Cerrar Sesion");
        jButton1_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_logoANDnameLayout = new javax.swing.GroupLayout(jPanel_logoANDname);
        jPanel_logoANDname.setLayout(jPanel_logoANDnameLayout);
        jPanel_logoANDnameLayout.setHorizontalGroup(
            jPanel_logoANDnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_logoANDnameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_appLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 689, Short.MAX_VALUE)
                .addComponent(jButton1_logout)
                .addContainerGap())
        );
        jPanel_logoANDnameLayout.setVerticalGroup(
            jPanel_logoANDnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_logoANDnameLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel_logoANDnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_logout)
                    .addComponent(jLabel_appLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_container.add(jPanel_logoANDname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1020, 60));

        jPanel_menu.setBackground(new java.awt.Color(51, 51, 51));

        Label_menuItem1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        Label_menuItem1.setForeground(new java.awt.Color(255, 255, 255));
        Label_menuItem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_menuItem1.setText("Dashboard");
        Label_menuItem1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        Label_menuItem2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        Label_menuItem2.setForeground(new java.awt.Color(255, 255, 255));
        Label_menuItem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_menuItem2.setText("Usuarios");

        Label_menuItem3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        Label_menuItem3.setForeground(new java.awt.Color(255, 255, 255));
        Label_menuItem3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_menuItem3.setText("Gestion de asistentes");

        Label_menuItem4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        Label_menuItem4.setForeground(new java.awt.Color(255, 255, 255));
        Label_menuItem4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_menuItem4.setText("Gestion de inscripciones");

        Label_menuItem5.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        Label_menuItem5.setForeground(new java.awt.Color(255, 255, 255));
        Label_menuItem5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_menuItem5.setText("Informacion de los asistentes");

        Label_menuItem6.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        Label_menuItem6.setForeground(new java.awt.Color(255, 255, 255));
        Label_menuItem6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_menuItem6.setText("Exportar");

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon("/home/p4prika/Documents/Github/Casa-Cultura-UAM/assets/casa_cultura_uamRedim.png")); // NOI18N
        jLabel29.setText("jLabel29");

        javax.swing.GroupLayout jPanel_menuLayout = new javax.swing.GroupLayout(jPanel_menu);
        jPanel_menu.setLayout(jPanel_menuLayout);
        jPanel_menuLayout.setHorizontalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_menuItem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Label_menuItem2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Label_menuItem3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Label_menuItem4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Label_menuItem5, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(Label_menuItem6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel_menuLayout.setVerticalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Label_menuItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_menuItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_menuItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_menuItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_menuItem5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_menuItem6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        jPanel_container.add(jPanel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 690));

        jPanel1_dashboard.setPreferredSize(new java.awt.Dimension(1020, 630));

        jPanel1_danza.setBackground(new java.awt.Color(255, 51, 51));

        jLabel6.setIcon(new javax.swing.ImageIcon("/home/p4prika/Documents/Github/Casa-Cultura-UAM/assets/taller_danza_logoRedim.jpg")); // NOI18N

        jLabel13.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Taller de Danza");

        jLabel14.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Inscritos: 12");

        javax.swing.GroupLayout jPanel1_danzaLayout = new javax.swing.GroupLayout(jPanel1_danza);
        jPanel1_danza.setLayout(jPanel1_danzaLayout);
        jPanel1_danzaLayout.setHorizontalGroup(
            jPanel1_danzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_danzaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1_danzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_danzaLayout.setVerticalGroup(
            jPanel1_danzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_danzaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1_teatro.setBackground(new java.awt.Color(255, 51, 51));

        jLabel8.setIcon(new javax.swing.ImageIcon("/home/p4prika/Documents/Github/Casa-Cultura-UAM/assets/taller_redaccion_logoRedim.jpg")); // NOI18N

        jLabel15.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Taller de Redaccion");

        jLabel16.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Inscritos: 10");

        javax.swing.GroupLayout jPanel1_teatroLayout = new javax.swing.GroupLayout(jPanel1_teatro);
        jPanel1_teatro.setLayout(jPanel1_teatroLayout);
        jPanel1_teatroLayout.setHorizontalGroup(
            jPanel1_teatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_teatroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1_teatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_teatroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1_teatroLayout.createSequentialGroup()
                        .addGroup(jPanel1_teatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1_teatroLayout.setVerticalGroup(
            jPanel1_teatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_teatroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1_dibujo.setBackground(new java.awt.Color(255, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/p4prika/Documents/Github/Casa-Cultura-UAM/assets/taller_teatro_logoRedim.jpg")); // NOI18N

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Taller de Teatro");

        jLabel12.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Inscritos: 18");

        javax.swing.GroupLayout jPanel1_dibujoLayout = new javax.swing.GroupLayout(jPanel1_dibujo);
        jPanel1_dibujo.setLayout(jPanel1_dibujoLayout);
        jPanel1_dibujoLayout.setHorizontalGroup(
            jPanel1_dibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_dibujoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1_dibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_dibujoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1_dibujoLayout.createSequentialGroup()
                        .addGroup(jPanel1_dibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1_dibujoLayout.setVerticalGroup(
            jPanel1_dibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_dibujoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1_readaccion.setBackground(new java.awt.Color(255, 51, 51));

        jLabel_inscritos_dibujo.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel_inscritos_dibujo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_inscritos_dibujo.setText("Inscritos: 17");

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Taller de Dibujo");

        jLabel4.setIcon(new javax.swing.ImageIcon("/home/p4prika/Documents/Github/Casa-Cultura-UAM/assets/taller_dibujo_logoRedim.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel1_readaccionLayout = new javax.swing.GroupLayout(jPanel1_readaccion);
        jPanel1_readaccion.setLayout(jPanel1_readaccionLayout);
        jPanel1_readaccionLayout.setHorizontalGroup(
            jPanel1_readaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_readaccionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_inscritos_dibujo)
                .addGap(227, 227, 227))
            .addGroup(jPanel1_readaccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1_readaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_readaccionLayout.setVerticalGroup(
            jPanel1_readaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_readaccionLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_inscritos_dibujo)
                .addGap(24, 24, 24))
        );

        jPanel1_lectura.setBackground(new java.awt.Color(255, 51, 51));

        jLabel9.setIcon(new javax.swing.ImageIcon("/home/p4prika/Documents/Github/Casa-Cultura-UAM/assets/taller_lectura_logoRedim.jpg")); // NOI18N

        jLabel17.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Taller de Lectura");

        jLabel18.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Inscritos: 15");

        javax.swing.GroupLayout jPanel1_lecturaLayout = new javax.swing.GroupLayout(jPanel1_lectura);
        jPanel1_lectura.setLayout(jPanel1_lecturaLayout);
        jPanel1_lecturaLayout.setHorizontalGroup(
            jPanel1_lecturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_lecturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1_lecturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_lecturaLayout.setVerticalGroup(
            jPanel1_lecturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_lecturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1_dashboardLayout = new javax.swing.GroupLayout(jPanel1_dashboard);
        jPanel1_dashboard.setLayout(jPanel1_dashboardLayout);
        jPanel1_dashboardLayout.setHorizontalGroup(
            jPanel1_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_dashboardLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel1_teatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1_lectura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_dashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1_danza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1_dibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1_readaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1_dashboardLayout.setVerticalGroup(
            jPanel1_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_dashboardLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1_danza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1_readaccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1_dibujo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1_teatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1_lectura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jPanel_container.add(jPanel1_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 1020, 630));

        jLabel3.setText("USUARIOS");

        javax.swing.GroupLayout jPanel2_usersLayout = new javax.swing.GroupLayout(jPanel2_users);
        jPanel2_users.setLayout(jPanel2_usersLayout);
        jPanel2_usersLayout.setHorizontalGroup(
            jPanel2_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_usersLayout.createSequentialGroup()
                .addGap(473, 473, 473)
                .addComponent(jLabel3)
                .addContainerGap(478, Short.MAX_VALUE))
        );
        jPanel2_usersLayout.setVerticalGroup(
            jPanel2_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_usersLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel3)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        jPanel_container.add(jPanel2_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 1020, 630));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton4_inscribir_taller.setBackground(new java.awt.Color(255, 51, 51));
        jButton4_inscribir_taller.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jButton4_inscribir_taller.setForeground(new java.awt.Color(255, 255, 255));
        jButton4_inscribir_taller.setText("Inscripcion a taller");
        jButton4_inscribir_taller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_inscribir_tallerActionPerformed(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon("/home/p4prika/Documents/Github/Casa-Cultura-UAM/assets/inscripcion_logoRedim.png")); // NOI18N

        jLabel25.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel25.setText("Inscribir al taller seleccionado");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                .addComponent(jButton4_inscribir_taller, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4_inscribir_taller, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jButton4_cancelar_inscripcion_taller.setBackground(new java.awt.Color(255, 51, 51));
        jButton4_cancelar_inscripcion_taller.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jButton4_cancelar_inscripcion_taller.setForeground(new java.awt.Color(255, 255, 255));
        jButton4_cancelar_inscripcion_taller.setText("Cancelar inscripcion a taller");
        jButton4_cancelar_inscripcion_taller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_cancelar_inscripcion_tallerActionPerformed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon("/home/p4prika/Documents/Github/Casa-Cultura-UAM/assets/cancelar_inscripcion_logoRedim.png")); // NOI18N

        jLabel24.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel24.setText("Dar de baja del taller");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4_cancelar_inscripcion_taller, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4_cancelar_inscripcion_taller, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4_inscripcion_asistentesLayout = new javax.swing.GroupLayout(jPanel4_inscripcion_asistentes);
        jPanel4_inscripcion_asistentes.setLayout(jPanel4_inscripcion_asistentesLayout);
        jPanel4_inscripcion_asistentesLayout.setHorizontalGroup(
            jPanel4_inscripcion_asistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4_inscripcion_asistentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4_inscripcion_asistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4_inscripcion_asistentesLayout.setVerticalGroup(
            jPanel4_inscripcion_asistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4_inscripcion_asistentesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        jPanel_container.add(jPanel4_inscripcion_asistentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 62, 1020, 630));

        jPanel3_registro_asistentes.setPreferredSize(new java.awt.Dimension(1020, 630));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton3_registrar_asistente.setBackground(new java.awt.Color(255, 51, 51));
        jButton3_registrar_asistente.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jButton3_registrar_asistente.setForeground(new java.awt.Color(255, 255, 255));
        jButton3_registrar_asistente.setText("Registrar un asistente");
        jButton3_registrar_asistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_registrar_asistenteActionPerformed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon("/home/p4prika/Documents/Github/Casa-Cultura-UAM/assets/create_logoRedim.png")); // NOI18N

        jLabel26.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel26.setText("Registrar nuevo asistente en el sistema");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(jButton3_registrar_asistente, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3_registrar_asistente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton3_actualizar_asistente.setBackground(new java.awt.Color(255, 51, 51));
        jButton3_actualizar_asistente.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jButton3_actualizar_asistente.setForeground(new java.awt.Color(255, 255, 255));
        jButton3_actualizar_asistente.setText("Actualizar informacion");
        jButton3_actualizar_asistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_actualizar_asistenteActionPerformed(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon("/home/p4prika/Documents/Github/Casa-Cultura-UAM/assets/delete_logoRedim.png")); // NOI18N

        jLabel27.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel27.setText("Modificar datos del asistente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3_actualizar_asistente, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3_actualizar_asistente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(40, 40, 40))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton3_eliminar_asistente.setBackground(new java.awt.Color(255, 51, 51));
        jButton3_eliminar_asistente.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jButton3_eliminar_asistente.setForeground(new java.awt.Color(255, 255, 255));
        jButton3_eliminar_asistente.setText("Eliminar un asistente");
        jButton3_eliminar_asistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_eliminar_asistenteActionPerformed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon("/home/p4prika/Documents/Github/Casa-Cultura-UAM/assets/update_logoRedim.png")); // NOI18N

        jLabel28.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel28.setText("Eliminar asistente registrado");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3_eliminar_asistente, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel28))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton3_eliminar_asistente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1))
                            .addComponent(jLabel21))))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel3_registro_asistentesLayout = new javax.swing.GroupLayout(jPanel3_registro_asistentes);
        jPanel3_registro_asistentes.setLayout(jPanel3_registro_asistentesLayout);
        jPanel3_registro_asistentesLayout.setHorizontalGroup(
            jPanel3_registro_asistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3_registro_asistentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3_registro_asistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3_registro_asistentesLayout.setVerticalGroup(
            jPanel3_registro_asistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3_registro_asistentesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        jPanel_container.add(jPanel3_registro_asistentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 61, 1020, 630));

        jPanel5_info.setPreferredSize(new java.awt.Dimension(1020, 630));

        jTable5_informacion_asistentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable5_informacion_asistentes);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );

        jLabel5.setText("Introduzca la matricula del asistente a buscar");

        jTextField5_info_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5_info_buscarActionPerformed(evt);
            }
        });

        jButton5_info_buscar.setBackground(new java.awt.Color(255, 51, 51));
        jButton5_info_buscar.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton5_info_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jButton5_info_buscar.setText("Buscar");
        jButton5_info_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_info_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5_infoLayout = new javax.swing.GroupLayout(jPanel5_info);
        jPanel5_info.setLayout(jPanel5_infoLayout);
        jPanel5_infoLayout.setHorizontalGroup(
            jPanel5_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5_infoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5_info_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5_info_buscar)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5_infoLayout.setVerticalGroup(
            jPanel5_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5_infoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5_info_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5_info_buscar))
                .addGap(34, 34, 34)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel_container.add(jPanel5_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 1020, -1));

        jLabel7.setText("EXPORTAR");

        javax.swing.GroupLayout jPanel6_exportarLayout = new javax.swing.GroupLayout(jPanel6_exportar);
        jPanel6_exportar.setLayout(jPanel6_exportarLayout);
        jPanel6_exportarLayout.setHorizontalGroup(
            jPanel6_exportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
            .addGroup(jPanel6_exportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6_exportarLayout.createSequentialGroup()
                    .addGap(473, 473, 473)
                    .addComponent(jLabel7)
                    .addContainerGap(474, Short.MAX_VALUE)))
        );
        jPanel6_exportarLayout.setVerticalGroup(
            jPanel6_exportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(jPanel6_exportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6_exportarLayout.createSequentialGroup()
                    .addGap(305, 305, 305)
                    .addComponent(jLabel7)
                    .addContainerGap(306, Short.MAX_VALUE)))
        );

        jPanel_container.add(jPanel6_exportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 1020, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_logoutActionPerformed
        // TODO add your handling code here:
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
                null,
                "¿Estás seguro de que deseas cerrar sesión?",
                "Cerrar Sesión",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            System.out.println("Sesión cerrada. Redirigiendo al login...");
            new LoginForm().setVisible(true);
            this.dispose();
            // Aquí puedes llamar a tu método para cerrar sesión o abrir la pantalla de login
        } else {
            System.out.println("Operación cancelada.");
        }


    }//GEN-LAST:event_jButton1_logoutActionPerformed

    private void jButton3_registrar_asistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_registrar_asistenteActionPerformed
        // TODO add your handling code here:
        // Deshabilitar el botón para que no puedan volver a presionarlo.
        jButton3_registrar_asistente.setEnabled(false);

        AnadirAsistente ventana = new AnadirAsistente();
        // Configurar para que NO cierre la aplicación cuando se cierre esta ventana.
        ventana.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        ventana.setVisible(true);

        ventana.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                jButton3_registrar_asistente.setEnabled(true);
            }
        });
    }//GEN-LAST:event_jButton3_registrar_asistenteActionPerformed

    private void jButton3_actualizar_asistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_actualizar_asistenteActionPerformed
        // TODO add your handling code here:
        // Deshabilitar el botón para que no puedan volver a presionarlo.
        jButton3_actualizar_asistente.setEnabled(false);

        //AnadirAsistente ventana = new AnadirAsistente();
        ActualizarAsistente ventana = new ActualizarAsistente();
        // Configurar para que NO cierre la aplicación cuando se cierre esta ventana.
        ventana.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        ventana.setVisible(true);

        ventana.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                jButton3_actualizar_asistente.setEnabled(true);
            }
        });
    }//GEN-LAST:event_jButton3_actualizar_asistenteActionPerformed

    private void jButton3_eliminar_asistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_eliminar_asistenteActionPerformed
        // TODO add your handling code here:
        // Deshabilitar el botón para que no puedan volver a presionarlo.
        jButton3_eliminar_asistente.setEnabled(false);

        //AnadirAsistente ventana = new AnadirAsistente();
        EliminarAsistente ventana = new EliminarAsistente();
        // Configurar para que NO cierre la aplicación cuando se cierre esta ventana.
        ventana.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        ventana.setVisible(true);

        ventana.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                jButton3_eliminar_asistente.setEnabled(true);
            }
        });
    }//GEN-LAST:event_jButton3_eliminar_asistenteActionPerformed

    private void jButton4_cancelar_inscripcion_tallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_cancelar_inscripcion_tallerActionPerformed
        // TODO add your handling code here:
        // Deshabilitar el botón para que no puedan volver a presionarlo.
        jButton4_cancelar_inscripcion_taller.setEnabled(false);

        //AnadirAsistente ventana = new AnadirAsistente();
        CancelarInscripcionTaller ventana = new CancelarInscripcionTaller();
        // Configurar para que NO cierre la aplicación cuando se cierre esta ventana.
        ventana.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        ventana.setVisible(true);

        ventana.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                jButton4_cancelar_inscripcion_taller.setEnabled(true);
            }
        });
    }//GEN-LAST:event_jButton4_cancelar_inscripcion_tallerActionPerformed

    private void jButton4_inscribir_tallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_inscribir_tallerActionPerformed
        // TODO add your handling code here:
        jButton4_inscribir_taller.setEnabled(false);

        //AnadirAsistente ventana = new AnadirAsistente();
        InscripcionTaller ventana = new InscripcionTaller();
        // Configurar para que NO cierre la aplicación cuando se cierre esta ventana.
        ventana.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        ventana.setVisible(true);

        ventana.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                jButton4_inscribir_taller.setEnabled(true);
            }
        });
    }//GEN-LAST:event_jButton4_inscribir_tallerActionPerformed

    private void jButton5_info_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_info_buscarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String matricula = jTextField5_info_buscar.getText().trim();
        if (matricula.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese una matrícula.", 
                                         "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        InscripcionReporte registro = inscripcionDAO.obtenerReporteInscripcionPorMatricula(matricula);
        if (registro != null) {
            String mensaje = String.format("Matrícula: %s\nNombre: %s %s\nTaller: %s\nHorario: %s\nCosto: %s",
                                          registro.getMatricula(),
                                          registro.getNombre(),
                                          registro.getPrimerApellido(),
                                          registro.getNombreTaller() != null ? registro.getNombreTaller() : "Sin taller",
                                          registro.getHorario() != null ? registro.getHorario() : "N/A",
                                          registro.getTotalAPagar() != null ? String.format("%.2f", registro.getTotalAPagar()) : "0.00");
            javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Información del Asistente", 
                                         javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró un alumno con la matrícula " + matricula, 
                                         "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5_info_buscarActionPerformed

    private void jTextField5_info_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5_info_buscarActionPerformed
        
    }//GEN-LAST:event_jTextField5_info_buscarActionPerformed
    
    public void cargarAsistentesEnTabla() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hacer todas las celdas no editables
            }
        };
        modelo.setColumnIdentifiers(new String[]{"Matrícula", "Nombre", "Primer Apellido", "Taller", "Horario", "Costo"});

        java.util.List<InscripcionReporte> reporte = inscripcionDAO.obtenerReporteInscripciones();
        for (InscripcionReporte registro : reporte) {
            modelo.addRow(new Object[]{
                registro.getMatricula(),
                registro.getNombre(),
                registro.getPrimerApellido(),
                registro.getNombreTaller() != null ? registro.getNombreTaller() : "Sin taller",
                registro.getHorario() != null ? registro.getHorario() : "N/A",
                registro.getTotalAPagar() != null ? String.format("%.2f", registro.getTotalAPagar()) : "0.00"
            });
        }

        jTable5_informacion_asistentes.setModel(modelo);
    }
    
    private void mostrarInformacionSeleccionada() {
        int selectedRow = jTable5_informacion_asistentes.getSelectedRow();
        if (selectedRow >= 0) {
            String matricula = (String) jTable5_informacion_asistentes.getValueAt(selectedRow, 0);
            String nombre = (String) jTable5_informacion_asistentes.getValueAt(selectedRow, 1);
            String primerApellido = (String) jTable5_informacion_asistentes.getValueAt(selectedRow, 2);
            String taller = (String) jTable5_informacion_asistentes.getValueAt(selectedRow, 3);
            String horario = (String) jTable5_informacion_asistentes.getValueAt(selectedRow, 4);
            String costo = (String) jTable5_informacion_asistentes.getValueAt(selectedRow, 5);

            // Opción 1: Mostrar en JOptionPane
            String mensaje = String.format("Matrícula: %s\nNombre: %s %s\nTaller: %s\nHorario: %s\nCosto: %s",
                                          matricula, nombre, primerApellido, taller, horario, costo);
            javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Información del Asistente", 
                                                     javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Opción 2: Actualizar JTextFields (descomenta si usas JTextFields)
            /*
            jTextFieldMatricula.setText(matricula);
            jTextFieldNombre.setText(nombre + " " + primerApellido);
            jTextFieldTaller.setText(taller);
            jTextFieldHorario.setText(horario);
            jTextFieldCosto.setText(costo);
            */
        }
    }
    
    public void busquedaDeAsistente(String matricula) {
        
        /*javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        //modelo.setColumnIdentifiers(new String[]{"Matrícula", "Nombre", "Apellido", "Teléfono", "Correo"});
        modelo.setColumnIdentifiers(new String[]{"Matrícula", "Nombre", "Primer Apellido", "Taller", "Horario", "Costo"});
        
        Asistente asistente = new Asistente();
        asistente = new AsistenteDAO().buscarAsistentePorMatricula(matricula);
        boolean encontrado = asistente != null;

        if (encontrado) {
            modelo.addRow(new Object[]{
                asistente.getMatricula(),
                asistente.getNombre(),
                asistente.getPrimerApellido(),
                asistente.getSegundoApellido(),
                asistente.getEdad(),
                asistente.getGenero(),
                asistente.getTelefonoContacto(),
                asistente.getTelefonoEmergencia(),
                asistente.getDireccion()
            });
        }

        jTable3_actualizar_asistentes.setModel(modelo);

        if (!encontrado) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró el registro.", "Búsqueda", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            deshabilitarTextFields();
        } else {
            habilitarTextFields();
            llenarTextFields(modelo.getDataVector().elementAt(0));
        }*/
    }
     
    public void setLabelBackround(javax.swing.JLabel label) {
        for (javax.swing.JLabel menuItem : menuLabels) {
            menuItem.setOpaque(true); // Asegurarse de que se puede pintar el fondo
            menuItem.setBackground(new Color(51, 51, 51)); // Fondo por defecto
            menuItem.setForeground(Color.WHITE);
        }
        label.setOpaque(true);
        label.setBackground(Color.WHITE);
        label.setForeground(Color.BLUE);  // Texto azul
    }

    public void showPanel(javax.swing.JPanel panel) {
        for (javax.swing.JPanel pnl : panels) {
            pnl.setVisible(false);
        }
        panel.setVisible(true);
    }

    public void addActionToMenuLabels() {
        Component[] components = jPanel_menu.getComponents();
        
        for (Component component : components) {
            if (component instanceof javax.swing.JLabel label && component != jLabel29) {

                label.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        setLabelBackround(label);
                        switch (label.getText().trim()) {
                            case "Dashboard" -> {
                                setTitle("Casa de la Cultura – UAM Azcapotzalco: Dashboard");
                                showPanel(jPanel1_dashboard);
                            }
                            case "Usuarios" -> {
                                setTitle("Casa de la Cultura – UAM Azcapotzalco: Usuarios");
                                showPanel(jPanel2_users);
                            }
                            case "Gestion de asistentes" -> {
                                setTitle("Casa de la Cultura – UAM Azcapotzalco: Gestion de asistentes");
                                showPanel(jPanel3_registro_asistentes);
                            }
                            case "Gestion de inscripciones" -> {
                                setTitle("Casa de la Cultura – UAM Azcapotzalco: Gestion de inscripciones");
                                showPanel(jPanel4_inscripcion_asistentes);
                            }
                            case "Informacion de los asistentes" -> {
                                cargarAsistentesEnTabla();
                                setTitle("Casa de la Cultura – UAM Azcapotzalco: Informacion de los asistentes");
                                showPanel(jPanel5_info);
                            }
                            case "Exportar" -> {
                                setTitle("Casa de la Cultura – UAM Azcapotzalco: Exportar");
                                showPanel(jPanel6_exportar);
                            }
                        }
                    }

                    @Override
                    public void mousePressed(MouseEvent e) {
                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                        label.setBorder(yellow_border);
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                        label.setBorder(default_border);
                    }
                });
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_menuItem1;
    private javax.swing.JLabel Label_menuItem2;
    private javax.swing.JLabel Label_menuItem3;
    private javax.swing.JLabel Label_menuItem4;
    private javax.swing.JLabel Label_menuItem5;
    private javax.swing.JLabel Label_menuItem6;
    private javax.swing.JButton jButton1_logout;
    private javax.swing.JButton jButton3_actualizar_asistente;
    private javax.swing.JButton jButton3_eliminar_asistente;
    private javax.swing.JButton jButton3_registrar_asistente;
    private javax.swing.JButton jButton4_cancelar_inscripcion_taller;
    private javax.swing.JButton jButton4_inscribir_taller;
    private javax.swing.JButton jButton5_info_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_appLogo;
    private javax.swing.JLabel jLabel_inscritos_dibujo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1_danza;
    private javax.swing.JPanel jPanel1_dashboard;
    private javax.swing.JPanel jPanel1_dibujo;
    private javax.swing.JPanel jPanel1_lectura;
    private javax.swing.JPanel jPanel1_readaccion;
    private javax.swing.JPanel jPanel1_teatro;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2_users;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel3_registro_asistentes;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel4_inscripcion_asistentes;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel5_info;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel6_exportar;
    private javax.swing.JPanel jPanel_container;
    private javax.swing.JPanel jPanel_logoANDname;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable5_informacion_asistentes;
    private javax.swing.JTextField jTextField5_info_buscar;
    // End of variables declaration//GEN-END:variables

}
